apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: xid-ee
data:
  nginx.conf: |
    #user nginx;    
    error_log  /var/log/nginx/error.log;
    worker_processes  1;
    events {
      worker_connections  1024;
    }

    http {
      client_max_body_size        3G;
      client_header_timeout       600s;
      client_body_timeout         600s;
      proxy_connect_timeout       600s;
      proxy_send_timeout          600s;
      proxy_read_timeout          600s;
      send_timeout                600s;
      large_client_header_buffers 8 16k;

      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
       
      access_log  /dev/stdout main; 
      
      include /etc/nginx/virtualhost/virtualhost.conf;
    }
  virtualhost.conf: |
    upstream web_server {
      server ent-cloud-web-svc.xid-ee.svc.cluster.local:3000;
    }

    upstream api_server {
      server ent-cloud-api-svc.xid-ee.svc.cluster.local:3333;
    }

    upstream user-testing-api_server {
      server ent-cloud-ut-svc.xid-ee.svc.cluster.local;
    }
    upstream user-testing-socket_server {
      server ent-cloud-ut-svc.xid-ee.svc.cluster.local:8081;
    }

    upstream analytics-web_server {
      server ent-analytics-web-svc.xid-ee.svc.cluster.local:8050;
    }

    upstream analytics-api_server {
      server ent-analytics-api-svc.xid-ee.svc.cluster.local:8000;
    }

    # gzip
    gzip on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 8192;
    gzip_types  text/plain text/css application/json application/javascript
                application/x-javascript text/xml application/xml
                application/xml+rss text/javascript application/font-woff2
                application/font-woff;
    # security
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=15768000";
    server_tokens off;

    # proxy
    proxy_http_version 1.1;
    proxy_redirect off;
    proxy_set_header Host				$host;
    proxy_set_header X-Real-IP			$remote_addr;
    proxy_set_header X-Forwarded-For	$proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy      true;

    # outdated agents
    map $http_user_agent $outdated {
        default                                                     0;
        "~MSIE [1-9]\."                                             1;
        "~MSIE 1[0-1]\."                                            1;
        "~Trident/[5-7]\."                                          1;
        "~Edge/1[0-7]\."                                            1;
        "~Mozilla.*Firefox/5[0-9]\."                                1;
        "~Mozilla.*Firefox/6[0-5]\."                                1;
        "~Opera.*Version/2[0-9]\."                                  1;
        "~Chrome/5[0-9]\."                                          1;
        "~Chrome/6[0-3]\."                                          1;
        "~.*(?=.Mac OS X).*(AppleWebKit.*Version\/[0-8]\..*Safari)" 1;
    }

    # For Websocket (User Research)
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    server {
        listen 80;
        # redirect to web
        location / {
            proxy_pass http://web_server;
        }

        # redirect to api
        location /api {
            proxy_set_header X-API-Prefix /api;
            rewrite ^/api/?(.*) /$1 break;
            proxy_pass http://api_server/;
        }        
        
        location /api/v1 {
            proxy_set_header X-API-Prefix /api/v1;
            rewrite ^/api/v1/?(.*) /$1 break;
            proxy_pass http://api_server/;
        }
        
        location /api/v2 {
            proxy_set_header X-API-Prefix /api/v2;
            rewrite ^/api/v2/?(.*) /$1 break;
            proxy_pass http://api_server/;
        }
        
        # redirect to api - from Studio >=7.0
        location /api/v3 {
            proxy_set_header X-API-Prefix /api/v3;
            rewrite ^/api/v3/?(.*) /$1 break;
            proxy_pass http://api_server/;
        }

        location ^~ /user-research/socket {
            rewrite ^/user-research/(.*)$ /$1 break;
            proxy_pass http://user-testing-socket_server;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

        location ^~ /user-research {
            rewrite ^/user-research/(.*)$ /$1 break;
            proxy_pass http://user-testing-api_server;
        }

        
        # analytics dashboard
        location /analytics {
            proxy_pass http://analytics-web_server/analytics;
        }
        location /api/analytics/ {
            proxy_pass http://analytics-api_server/;
        }
        
        # robots.txt
        location = /robots.txt {
            root /usr/share/nginx/html/nginx-html/;
        }
        
        # static pages
        location ~ ^/(.well-known|outdated)/ {
            root /usr/share/nginx/html/nginx-html/;
        }

        # redirect as outdated browser has been connected
        if ($outdated = 1) {
            rewrite ^ /outdated/outdated.html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: xid-ee
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        company: xid-ee
      containers:
        - name: nginx
          image: 794161565898.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:1.29.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx # mount nginx-conf volume to /etc/nginx
              readOnly: true
            - name: log
              mountPath: /var/log/nginx
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: virtualhost.conf
                path: virtualhost/virtualhost.conf # dig directory
        - name: log
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: xid-ee
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthy
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 31030
      protocol: TCP
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sd
  namespace: xid-ee
  annotations:
    external-dns.alpha.kubernetes.io/access: private
    external-dns.alpha.kubernetes.io/hostname: xid-ee.protopie.internal
    external-dns.alpha.kubernetes.io/set-identifier: xid-ee
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
